sst dataset
bigscience-workshop/promptsource pull request #100
Opened 2021-06-07 14:48 UTC by arunraja-hub

2021-06-07 20:03 UTC, srush requested changes

2021-06-07 20:03 UTC, srush commented on templates/sst/default/templates.yaml
> +    jinja: 'How positive is the sentence below?
Let's say "How positive is the movie review below?"

2021-06-07 20:03 UTC, srush commented on templates/sst/default/templates.yaml
> +    jinja: 'Is the sentence below positive?
movie review

2021-06-07 20:03 UTC, srush commented on templates/sst/dictionary/templates.yaml
> +    jinja: 'Is the word or phrase below positive?
-> "in the context of a movie review"

2021-06-07 20:03 UTC, srush commented on templates/sst/default/templates.yaml
> +    jinja: 'Tokenize the sentence below:
Tokenization is a bit difficult to define. Let's remove this one.

2021-06-07 20:03 UTC, srush commented on templates/sst/default/templates.yaml
> +      Tree: {{tree}}'
I am not sure this one is working. The tree looks a bit odd?

2021-06-08 15:05 UTC, srush approved these changes

2021-06-08 15:08 UTC, srush commented on templates/sst/default/templates.yaml
> +      {{label}}'
I just realized that this label is a fraction. Can you convert it into an integer between 1 through 5

2021-06-08 15:09 UTC, srush commented on templates/sst/default/templates.yaml
> +    jinja: "Form a sentence parse tree (formatted as a parent pointer tree) using\
Can you add spaces in this parse? It seems very hard for a language model to get this.

2021-06-08 18:46 UTC, srush commented
Looks good. Not sure why there is a conflict though

2021-06-09 15:03 UTC, arunraja-hub commented
opened a new PR https://github.com/bigscience-workshop/promptsource/pull/134 to avoid conflicts
closing this

2021-06-09 15:03 UTC, closed without merging