prompt nlu_evaluation_data
bigscience-workshop/promptsource pull request #132
Opened 2021-06-09 14:34 UTC by zaidalyafeai

2021-06-09 16:16 UTC, VictorSanh commented on templates/nlu_evaluation_data/templates.yaml
> +    jinja: "Given the following text, what is the scenario ? \n{{text}}\n|||\n{{\n\
Use as little "linguistic terminology" as possible. You should replace the word "scenario" with something more explicit (layman's terms)! `nlu_eval_data_2` is a great example!

2021-06-09 16:16 UTC, VictorSanh commented on templates/nlu_evaluation_data/templates.yaml
> +    jinja: "This text describes what {{\"scenario\"}} ? \n{{text}}\n|||\n{{\n[\n \
What {{"scenario"}} does this text describe?

2021-06-09 16:16 UTC, VictorSanh commented on templates/nlu_evaluation_data/templates.yaml
> +    jinja: "Which {{\"scenario\"}} from the following: {{ ['music', 'news', 'alarm',\
from the following choices ( the choices) best describe

2021-06-09 16:16 UTC, VictorSanh commented on templates/nlu_evaluation_data/templates.yaml
> +    jinja: "The following piece of text, talks about what {{\"scenario\"}} ? \n{{text}}\n\
What {{"scenario"}} does the following piece of text talk about?

2021-06-09 16:22 UTC, VictorSanh requested changes
Thank you @zaidalyafeai !

Can you re-equilibrate to have more templates where you give the model the classes to choose from?

Another template I just thought about is something like:
```jinja
The virtual assistant received this query: {{text}}.
What skill should it activate among these choices: {{["alarm", ...]}}|||
{{ list[label].split("_")[0] }}
```
Could you add it? Feel free to be creative!

2021-06-09 18:04 UTC, zaidalyafeai commented
> Thank you @zaidalyafeai !
> 
> Can you re-equilibrate to have more templates where you give the model the classes to choose from?
> 
> Another template I just thought about is something like:
> 
> ```
> The virtual assistant received this query: {{text}}.
> What skill should it activate among these choices: {{["alarm", ...]}}|||
> {{ list[label].split("_")[0] }}
> ```
> 
> Could you add it? Feel free to be creative!

Thanks @VictorSanh , tried my best to respond to the review.

2021-06-09 18:25 UTC, VictorSanh commented
Thank you!

Re on the use of linguistic terms -> can we remove the word "scenario" whenever we don't have the whole list of choices (for instance `nlu_eval_data_4`)? Either we replace "scenario" with a descriptive text or we have the list of choices. My rule of thumb: if I saw this query, would I be able to give a reasonable answer without knowing about this particular dataset?

2021-06-09 19:02 UTC, zaidalyafeai commented
Thanks @VictorSanh, that makes sense. Maybe we could replace all occurrences of scenario with service ? An example might be "What service should be started when a user issues the following query ? " Not sure, though.

2021-06-09 22:22 UTC, VictorSanh commented
> Thanks @VictorSanh, that makes sense. Maybe we could replace all occurrences of scenario with service ? An example might be "What service should be started when a user issues the following query ? " Not sure, though.

Yes I am more comfortable with this!

2021-06-10 08:23 UTC, zaidalyafeai commented
@VictorSanh I rephrased all the occurrences to be more reasonable.

2021-06-10 13:40 UTC, VictorSanh approved these changes
thank you, merging now, please update the spreadsheet!

2021-06-10 13:40 UTC, merged