Templates for stsb_multi_mt_en
bigscience-workshop/promptsource pull request #160
Opened 2021-06-10 08:51 UTC by NohTow

I tried to write templates for stsb_multi_mt (the english subset).
There is some that ask for the numerical score and others that are in the form of yes/no using a threshold (see my question on slack).

2021-06-10 17:47 UTC, stephenbach requested changes
Great, thanks! Just a few minor clean ups and suggestions.

2021-06-10 17:47 UTC, stephenbach commented on templates/stsb_multi_mt/en/templates.yaml
> +      \ and {[\"5.0\"}} the highest)\n\"{{sentence1}}\" and \"{{sentence2}}\" \n|||\n\
Should be `{{"5.0"}}`

2021-06-10 17:47 UTC, stephenbach commented on templates/stsb_multi_mt/en/templates.yaml
> +      "{{sentence2}}" are ? ||| {{((5*similarity_score)|round)/5}}
Maybe more natural to say "how similar are X and Y?"

2021-06-10 17:47 UTC, stephenbach commented on templates/stsb_multi_mt/en/templates.yaml
> +      if similarity_score < 2.5 else 1]}}'
Extra `'` on the end

2021-06-10 17:47 UTC, stephenbach commented on templates/stsb_multi_mt/en/templates.yaml
> +      ||| {{["no","yes"][0 if similarity_score < 2.5 else 1]}}'
Extra `'` on the end

2021-06-11 16:00 UTC, NohTow commented
Fixed these issues (sorry for the typos, I don't know why I didn't see them...) and checked the main task box.

2021-06-11 16:45 UTC, stephenbach commented
Perfect, thanks!

2021-06-11 16:45 UTC, merged