Templates for spider
bigscience-workshop/promptsource pull request #162
Opened 2021-06-10 12:00 UTC by NohTow

Templates for the spider dataset.
One major issue was the variation in the writing style of question (some are not really "questions"), so I tried to make it sounds like exercise statements, hope it is good enough.

2021-06-10 21:31 UTC, srush requested changes
These are great. But can you also include the reverse entries. "I would describe the SQL statement ... to a new learner as ||| ..."

2021-06-10 21:31 UTC, srush commented on templates/spider/templates.yaml
> +    jinja: Can you give me the SQL request which respond to "{{question}}" ? ||| {{query}}
Respond should be "corresponds"

2021-06-10 21:31 UTC, srush commented on templates/spider/templates.yaml
> +    jinja: The SQL query associated to the question "{{question}}" is ||| {{query}}
"associated with"

2021-06-10 21:31 UTC, srush commented on templates/spider/templates.yaml
> +    jinja: 'To respond to "{{question}}", I can use the SQL query: ||| {{query}}'
Instead of "respond to" , I would say "lookup "

2021-06-11 15:48 UTC, NohTow commented
I added your corrections/recommendations and checked the main task box.
I also added the reverse entries, feel free to tell me if something is odd.

2021-06-11 18:55 UTC, merged