Add asset prompt for rating/simplification subsets
bigscience-workshop/promptsource pull request #169
Opened 2021-06-10 15:14 UTC by thomasw21

2021-06-11 22:03 UTC, VictorSanh commented on templates/asset/ratings/templates.yaml
> +      \ the best.\",  \"the second sentence if more fluent.\", \"the second sentence\
**is** more fluent

2021-06-11 22:05 UTC, VictorSanh commented on templates/asset/ratings/templates.yaml
> +    task_template: false
this template looks like the original task to me right? if so, it should be `true`

2021-06-11 22:08 UTC, VictorSanh commented on templates/asset/simplification/templates.yaml
> +      {{simplifications[random_simplification_id]}}"
let's simplify the jinja:
```jinja
{{original}}
How would I say this in another way?|||
{{simplifications | choice}}
```

2021-06-11 22:08 UTC, VictorSanh commented on templates/asset/simplification/templates.yaml
> +    task_template: false
looks like the origianl task to me

2021-06-11 22:09 UTC, VictorSanh commented on templates/asset/simplification/templates.yaml
> +      \ this in another way? \n\n|||\n\n{{original}}"
same comment on the jinja

2021-06-11 22:09 UTC, VictorSanh commented on templates/asset/simplification/templates.yaml
> +    task_template: false
true task

2021-06-11 22:10 UTC, VictorSanh commented on templates/asset/simplification/templates.yaml
> +      \ this in another way? \n\n|||\n\n{{original}}"
same for `asset_simplification3`

2021-06-11 22:14 UTC, VictorSanh requested changes
Thanks @thomasw21 !

I kind of feel like the "simplified" versions don't look that much simplified so "say it differently" looks good to me!

Left a few comments
Ping me when you have addressed them, will merge then!

2021-06-11 22:17 UTC, VictorSanh commented
A funky one that you can add for ratings is:

```jinja
First sentence: {{original}}
Second sentence: {{simplification}}
I am scoring these simplification exercises. How easier to read is the second sentence on a scale from 0 (harder to read) to 100 (easier to read)?|||
{{rating}}
```

2021-06-14 08:35 UTC, thomasw21 commented
@VictorSanh I've addressed your comments, and added your template as per your suggestion (though I'm not exactly sure how different the prompt is from `asset_ratings2`).

2021-06-14 18:20 UTC, VictorSanh approved these changes
merging now, please update the spreadsheet!

2021-06-14 18:20 UTC, merged