Prompts for generated_reviews_enth
bigscience-workshop/promptsource pull request #171
Opened 2021-06-10 15:46 UTC by NohTow

Prompts for the generated_reviews_enth dataset.
Since we only focus on english task, I did not consider translation/translation rating, only sentiment analysis of the english review.
I took inspiration from another templates I created for stsb_multi_mt (PR : https://github.com/bigscience-workshop/promptsource/pull/160)

As a sidenote, I just thought that an easy way to add prompts "for free" is to "inverse" the classification/prompt.
E.g, for "On a scale of 1 to 5, how positive is the review {{review}} ||| {{score}}", create also "On a scale of 1 to 5, how negative is the review {{review}} ||| {{6 - score}}" and inverse yes/no answer in the binary case.
Is it useful/profitable or is it better to just keep this version ?

2021-06-10 20:56 UTC, srush requested changes
These seems good. Feel free to be more creative with the questions. Remember that you are explaining the task to a human. 

I don't think you need to have negative versions, but you can include them if you have time.

2021-06-10 20:56 UTC, srush commented on templates/generated_reviews_enth/templates.yaml
> +    jinja: Do "{{translation.en}}" seems like a positive review to you? ||| {{["no","yes"][0
Grammar-> does the review ... Seem.

2021-06-10 20:56 UTC, srush commented on templates/generated_reviews_enth/templates.yaml
> +    jinja: On a scale from {{"1"}} to {{"5"}}, how positive the review "{{translation.en}}"
Grammar- "how positive is the review"

2021-06-11 15:24 UTC, NohTow commented
I fixed these grammar issues (sorry about that) and checked the "original task" box for every prompt.

2021-06-15 23:04 UTC, srush approved these changes

2021-06-15 23:04 UTC, merged