commonsense_qa
bigscience-workshop/promptsource pull request #178
Opened 2021-06-10 18:23 UTC by arunraja-hub

2021-06-11 03:33 UTC, arunraja-hub commented
Thank you. I have added more prompts. One of them is a variant where all the false answers have to be chosen. I feel that having yes/no will make all the answers as yes which could lead to severe imbalance and the options are also not polar opposites or binary in nature like 'cup' and 'bowl' which might not make sense for the model

2021-06-11 18:30 UTC, craffel requested changes

2021-06-11 18:30 UTC, craffel commented on templates/commonsense_qa/templates.yaml
> +      <b>{{choices[''label''][i]}}</b>: {{choices[''text''][i]}}
Can you remove this HTML markup? The model will only be able to process plain text.

2021-06-14 17:29 UTC, merged

2021-06-14 17:30 UTC, craffel commented
Thanks!