Winograd wsc
bigscience-workshop/promptsource pull request #182
Opened 2021-06-10 18:44 UTC by arunraja-hub

2021-06-10 21:52 UTC, srush requested changes
Small changes

2021-06-10 21:52 UTC, srush commented on templates/commonsense_qa/templates.yaml
> +      {% for i in range(choices[''text'']|length) %}
You should use {{choices["text"] | join("...")}} for this.

2021-06-10 21:52 UTC, srush commented on templates/winograd_wsc/wsc273/templates.yaml
> +      \ options are:\n{% for i in range(options|length) %}\n- {{options[i]}}\n{% endfor\
Join

2021-06-11 03:03 UTC, arunraja-hub commented
@srush I accidentally added the commonsense_qa file in this PR for which you have added the comment. Now I have removed it. Could you help to review this again please?

2021-06-11 17:56 UTC, srush commented
I don't think my comments above were addressed yet? Use join instead of for.

2021-06-13 22:43 UTC, merged