Prompts for `gutenberg_time`
bigscience-workshop/promptsource pull request #191
Opened 2021-06-11 07:29 UTC by drugilsberg

The dataset is super interesting. I initially tried to use the `is_ambiguous` flag to create more interesting prompts where the there was uncertainty on the time of the day (e.g., 5:00 vs. 17:00), but unfortunately after looking at the first 100 examples I realized that it is not reliable. I decided to use the time as is reported, because it seemed more accurate.

2021-06-11 19:37 UTC, VictorSanh commented on templates/gutenberg_time/templates.yaml
> +      It indicates to {{hour_reference}}:00.'
no need for "to" i believe

2021-06-11 19:40 UTC, VictorSanh requested changes
- remove `:00` as it is incorrect quite frequently
<img width="647" alt="Capture d’écran 2021-06-11 à 3 38 27 PM" src="https://user-images.githubusercontent.com/16107619/121740448-18e89680-cacb-11eb-89ea-1ab16f244f75.png">

- when the question is simple (what time), no need to write "It indicates .." or "The time reference reported is" and go directly to the answer as the preceding text doesn't provide much signal

2021-06-11 20:03 UTC, VictorSanh commented
> * when the question is simple (what time), no need to write "It indicates .." or "The time reference reported is" and go directly to the answer as the preceding text doesn't provide much signal

Actually a better strategy would be to move the `|||` and include the "in indicates.." in the prompt and leave only the prediction in the label part. This paradigm greatly simplifies evaluation in the general case. 
So for instance, this would look like `It indicates to ||| {{hour_reference}}:00.'` instead of `||| It indicates to {{hour_reference}}:00.'`

2021-06-11 22:32 UTC, drugilsberg commented
Thanks for the review @VictorSanh, I implemented the suggested changes. What should I do with the templates: `asking_the_time_reference_and_actual_time_before`, `asking_the_time_reference_and_actual_time_after`?
There it's not clear how to only leave the phrase and the reference after `|||`. Are they ok as is? Should I change them?

2021-06-12 22:01 UTC, VictorSanh approved these changes
looks good to me, merging now, thank you @drugilsberg , please update the spreadsheet!

Nothing much to do for `asking_the_time_reference_and_actual_time_before` and `asking_the_time_reference_and_actual_time_after`, let leave it like this

I replaced "time" by "hour (between 0 and 23)" when necessary

2021-06-12 22:02 UTC, merged

2021-06-12 22:13 UTC, drugilsberg commented
> looks good to me, merging now, thank you @drugilsberg , please update the spreadsheet!
> 
> Nothing much to do for `asking_the_time_reference_and_actual_time_before` and `asking_the_time_reference_and_actual_time_after`, let leave it like this
> 
> I replaced "time" by "hour (between 0 and 23)" when necessary

Thanks to you will update now.