Add template for onestop_english dataset
bigscience-workshop/promptsource pull request #198
Opened 2021-06-11 15:13 UTC by trishalaneeraj

2021-06-11 21:14 UTC, VictorSanh commented on templates/onestop_english/templates.yaml
> +      {{ ["ele", "int", "adv"] [label] }}'
replace "ele" by "elementary", "int" by "intermediate", etc. in both the prompt and the label

2021-06-11 21:15 UTC, VictorSanh commented on templates/onestop_english/templates.yaml
> +      Choose from one of {{"ele"}}, {{"int"}} or {{"adv"}} levels?
no need for `?`

2021-06-11 21:16 UTC, VictorSanh commented on templates/onestop_english/templates.yaml
> +      as their second language, how are they likely to rate the difficulty level of
how are they likely **going**

2021-06-11 21:16 UTC, VictorSanh commented on templates/onestop_english/templates.yaml
> +      {{ ["ele", "int", "adv"] [label] }}'
same for all templates

2021-06-11 21:17 UTC, VictorSanh requested changes
Thank you @trishalaneeraj !

a few comments, please ping me when you addressed them, I'll merge then!

2021-06-12 02:39 UTC, trishalaneeraj commented
@VictorSanh Thanks! I've addressed the comments above.

2021-06-12 23:44 UTC, VictorSanh approved these changes
thank you! please update the spreadsheet
merging now

2021-06-12 23:45 UTC, merged