Add template for emo dataset
bigscience-workshop/promptsource pull request #199
Opened 2021-06-11 15:46 UTC by trishalaneeraj

2021-06-11 21:25 UTC, VictorSanh commented on templates/emo/templates.yaml
> +      {{ ["others", "happy", "sad", "angry"] [label] }}'
for all templates, please change to "something else" as it is the choice described in the prompt

2021-06-11 21:27 UTC, VictorSanh commented on templates/emo/templates.yaml
> +      else"}}?
That doesn't correctly explain the task: you don't see it's a dialogue, there is no context/dialogue history.
Better: `This is an extract of a dialogue between two people. Which of the following options best describes the emotion the speaker is feeling?`

2021-06-11 21:30 UTC, VictorSanh requested changes
thank you @trishalaneeraj, this one is weird because the dialogue is concatenaneted (and not separated in any way...).
One small comment.
please ping me when it is addressed and I'll merge!

2021-06-12 02:22 UTC, trishalaneeraj commented
@VictorSanh thanks! I've made the change.

2021-06-12 23:52 UTC, VictorSanh approved these changes
thank you!
merging now, please update the spreadsheet!

2021-06-12 23:52 UTC, merged