Add acronym_identification templates
bigscience-workshop/promptsource pull request #201
Opened 2021-06-11 16:30 UTC by gchhablani

Possible templates which I haven't added -
1. Given the text and abbreviation, find the expansion. (Model needs to detect start and end).
2. Given the text and expansion, find the abbreviation. (Model needs to decide which abbreviation is to be chosen - non-trivial as the model needs to remember positions).

The following cases can occur in the given dataset:
- <some text> Exp (Abbr) <some text>  Exp (Abbr) <some text>
-  <some text> Abbr (Exp) <some text>  Abbr (Exp) <some text>
-  <some text> Abbr (Exp) <some text>  Abbr <some text>

It is easy to get all the abbreviations and expansions (see current templates).

I was wondering if the following logic will work:
```
- Generate the {acronym:expansion} dictionary using the following logic:
    - Keep two string variables - one for acronym, and one for expansion
    - Keep two more int variables that store the last index at which the expansion/acronym is found.
    - Whenever both are non-empty: 
        - Check the distance between the last index at which they are found, if not greater than 2, these two pairs match - add to the dictionary.  Set both variables to empty.
        - Otherwise, the oldest abbreviation must be discarded as a new abbreviation is coming up.
 ```
I'm not sure if this will work correctly, wdyt?

2021-06-16 19:19 UTC, VictorSanh requested changes
waoo this one is very hard!
thanks for taking it @gchhablani !

Made a few suggestions/changes

2021-06-16 19:19 UTC, VictorSanh commented on templates/acronym_identification/templates.yaml
> +      {% else %}\n|||\n{% endif %}"
bring the `|||` out of the your if condition. if the template is blank, it should return an empty string `` and then through the `.split("|||")` it should be `[""]`

2021-06-16 19:19 UTC, VictorSanh commented on templates/acronym_identification/templates.yaml
> +      \ %}\nGiven the following tokens, find the expansion of {{random_abbr}}:\n \n\
```suggestion
      \ %}\nGiven the following tokens, find the expansion of {{random_abbr}}. Return "Unclear" if the expansion can't be found.\n \n\
```

2021-06-16 19:19 UTC, VictorSanh commented on templates/acronym_identification/templates.yaml
> +      \ %}\nGiven the following tokens, find the expansion of {{random_abbr}}:\n \n\
please do similar modification for `find_abbreviation`

2021-06-16 19:19 UTC, VictorSanh commented on templates/acronym_identification/templates.yaml
> +      \ : {{value}}\n{%endfor%}"
maybe an "unclear" if can't find the abbeviation?
<img width="668" alt="Capture d’écran 2021-06-16 à 3 16 24 PM" src="https://user-images.githubusercontent.com/16107619/122279322-ea493200-ceb5-11eb-9481-442a0ab45a22.png">

2021-06-16 19:19 UTC, VictorSanh commented on templates/acronym_identification/templates.yaml
> +      \ %}\nGiven the following tokens, find the expansion of {{random_abbr}}:\n \n\
and for `list_expansions` ("No expansions found")

2021-06-17 00:19 UTC, gchhablani commented on templates/acronym_identification/templates.yaml
> +      \ comma-separated tokens: \n\n{{tokens|join(', ')}}.\n|||\n{% for label in labels\
All the tokens I have seen usually have their own ".". I think this could be redundant?

2021-06-17 18:44 UTC, VictorSanh commented on templates/acronym_identification/templates.yaml
> +      {% else %}\n|||\n{% endif %}"
seems like it's persisting:
<img width="669" alt="Capture d’écran 2021-06-17 à 2 27 37 PM" src="https://user-images.githubusercontent.com/16107619/122455373-50978880-cf7a-11eb-9201-b69c1d4ff89e.png">

It should literally be displaying `∅∅∅ *Blank result*` (see https://github.com/bigscience-workshop/promptsource/blob/main/promptsource/promptsource.py#L303)
and I think right now there are a lot of "\n" in what's being returned...

2021-06-18 17:48 UTC, VictorSanh commented
note: weird formatting of jinja. merging for now, will fix later

2021-06-18 17:48 UTC, merged