cord19 templates
bigscience-workshop/promptsource pull request #229
Opened 2021-06-13 17:13 UTC by srulikbd

hope its good!
if not, send me a messege!

2021-06-14 18:40 UTC, VictorSanh commented
to err on the safe side, let' skip `hate_speech18` as it clearly contains harmful content (extracted from a white supremacist forum...) can you remove it from the pr and mark it as "harmful content" in the spreadsheet?
reviewing the rest

2021-06-14 19:02 UTC, VictorSanh requested changes
left comments. see above.

please remove "false" tasks where we know the answer independently of the example.

2021-06-14 19:02 UTC, VictorSanh commented on templates/cord19/metadata/templates.yaml
> +    jinja: "{{title}}\nThe abstract of this title is:  |||\n {{ abstract }}"
Replace with:
```jinja
Title: {{title}}
Generate a plausible scientific abstract for a scientific paper on Covid-19 with the previous title
```

2021-06-14 19:02 UTC, VictorSanh commented on templates/cord19/metadata/templates.yaml
> +      The title of this abstract is:  |||
`What could a scientific title be for this abstract on Covid-19?`

2021-06-15 11:57 UTC, closed without merging

2021-06-15 11:58 UTC, srulikbd commented
I made a new PR based on your comments..thanks!!