Add prompts for humicroedit dataset
bigscience-workshop/promptsource pull request #263
Opened 2021-06-15 10:42 UTC by HanNight

2021-06-15 23:41 UTC, srush requested changes
These are good prompts! Hard to do.

2021-06-15 23:41 UTC, srush commented on templates/humicroedit/subtask-1/templates.yaml
> +    jinja: 'Please rate how funny the sentence after replacing the "{{ original[original.index("<")+1:original.index("/>")]
This one is grammatically off. Also the examples are difficult to read since the replacement comes after the sentence.

2021-06-15 23:41 UTC, srush commented on templates/humicroedit/subtask-1/templates.yaml
> +    jinja: 'I need to know how funny the sentence after replacing the "{{ original[original.index("<")+1:original.index("/>")]
Grammar

2021-06-15 23:41 UTC, srush commented on templates/humicroedit/subtask-1/templates.yaml
> +    jinja: 'I need to know how funny the edited sentence is based on the original
"based on" maybe compared to?

2021-06-15 23:41 UTC, srush commented on templates/humicroedit/subtask-2/templates.yaml
> +      }}" with "{{ edit2 }}", or both are the same humorous?
"or are both equally funny?"

2021-06-16 06:19 UTC, HanNight commented
Thanks for your suggestion, I have modified it.

2021-06-17 21:35 UTC, srush approved these changes

2021-06-17 21:35 UTC, merged