add Trivia-QA dataset
bigscience-workshop/promptsource pull request #277
Opened 2021-06-17 23:44 UTC by sbmaruf

2021-06-17 23:46 UTC, sbmaruf commented
@VictorSanh  Please take a look here. I closed the previous pull.

2021-06-18 02:26 UTC, VictorSanh requested changes
thank you @sbmaruf , please see my comments

TriviaQA is initially intended as a reading comprehension task (not a closed-book qa task), so:
- please correct the `task_template` flags
- add templates that actually leverage the multiple context provided (I am not sure which one should be used but there is at least `entity_pages.wiki_context`, `search_results.description`,  and `search_results.search_context`)

Also, use `choice` instead of listing of all (potentially repetitive) options

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
it's a reading comprehension dataset
```suggestion
    task_template: false
```

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
hmm quite confused about this one
the model won't be able to technically search Wikipedia.
You should transform this into `Here's what I found on the internet:... please answer the question`

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
same for `context_self_description_wikipedia_2`

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
you can remove this one, i am very not sure of the signal it brings and it doesn't make sense from the evaluation perspective

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    jinja: Guess a question from the topic "{{answer.aliases|choice}} " ||| {{question}}
```suggestion
    jinja: Guess a question from the topic "{{answer.aliases|choice}}" |||{{question}}
```

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    jinja: 'Question : {{question}} {{"\n"}} Answer : ||| {{answer.aliases|choice}} '
```suggestion
    jinja: 'Question : {{question}} \nAnswer: |||{{answer.aliases|choice}} '
```

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
same for `question_multiple_valid_answer`

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    jinja: 'Answer the following question. {{"\n"}} {{question}} ||| {{answer.aliases|choice}} '
```suggestion
    jinja: 'Answer the following question. \n{{question}} |||{{answer.aliases|choice}} '
```

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
same for `question_with_instruction_multiple_valid_answer`

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
same for `wikipedia_contextual_question`

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
and `wikipedia_contextual_question_multiple_answer`

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
same for `wikipedia_question`

2021-06-18 02:26 UTC, VictorSanh commented on templates/trivia_qa/rc/templates.yaml
> +    task_template: true
and `wikipedia_question_multiple_answer`

2021-06-18 09:42 UTC, sbmaruf commented
@VictorSanh Can you take a look? Let me know if you find any issues.

2021-06-18 12:02 UTC, VictorSanh approved these changes
thank you @sbmaruf , please update the spreadsheet, merging now

2021-06-18 12:03 UTC, merged