Clean cosmos_qa
bigscience-workshop/promptsource pull request #368
Opened 2021-09-09 01:24 UTC by nihalnayak

add accuracy and template description for cosmos_qa

2021-09-09 14:48 UTC, awebson commented
Should `Answer Choices` be separated by `|||` not commas?

2021-09-09 14:51 UTC, stephenbach commented
Yes, that's right. Separate with `|||`

2021-09-09 18:53 UTC, awebson requested changes
@nihalnayak can you double check the original task flags? For example, isn't context_description_question_answer_text the original task of QA?

2021-09-09 20:28 UTC, nihalnayak commented
> @nihalnayak can you double check the original task flags? For example, isn't context_description_question_answer_text the original task of QA?
Thanks for flagging this issue. Should I convert this to an original task even though this is a generation task? Should the metric be accuracy instead of ROUGE/BLEU?

2021-09-09 22:48 UTC, awebson commented
No you can just leave the generation templates as they are, but just uncheck their "original task" boxes. Meanwhile, for the QA templates, check their "original task" boxes. Thanks!

2021-09-10 23:21 UTC, awebson requested changes
Could you please also add the `answer_choices_keys` according to #373 ?

2021-09-11 00:11 UTC, awebson approved these changes

2021-09-11 00:11 UTC, awebson commented on promptsource/templates/cosmos_qa/templates.yaml
> +      - BLEU
```suggestion
      - Accuracy
```

2021-09-11 00:11 UTC, awebson commented on promptsource/templates/cosmos_qa/templates.yaml
> +      - ROUGE
```suggestion
```

2021-09-11 00:11 UTC, awebson commented on promptsource/templates/cosmos_qa/templates.yaml
> +      - BLEU
```suggestion
      - Accuracy
```

2021-09-11 00:11 UTC, awebson commented on promptsource/templates/cosmos_qa/templates.yaml
> +      - ROUGE
```suggestion
```

2021-09-11 00:11 UTC, awebson commented on promptsource/templates/cosmos_qa/templates.yaml
> +      - BLEU
```suggestion
      - Accuracy
```

2021-09-11 00:11 UTC, awebson commented on promptsource/templates/cosmos_qa/templates.yaml
> +      - ROUGE
```suggestion
```

2021-09-11 00:15 UTC, merged