Cleanup pass on sciq, wiki_bio, scitail
bigscience-workshop/promptsource pull request #388
Opened 2021-09-10 06:47 UTC by jason-fries

Added new templates to sciq and scitail to bring us up to 5 templates
Rephrases the "who" template in wiki_bio

2021-09-10 14:04 UTC, awebson requested changes
Thanks! For sciq, could you please:

1. Add the answer_choices_key according to #373
2. In multiple choice prompts, replace your answer deliminator with commas and space, or a bullet list. Right now simply using `|` with no space is not natural English and might cause problems for the tokenizer.
3. For your Direction Question prompt, uncheck `choices in prompts`.

For SciTail: Please note that entailment is always annotated as unidirectional, so it's ill-defined to ask what is the entailment label of a sentence pair without specifying the direction (even though they may be pragmatically inferred). Also, we should provide more explanations on what does "entail" even mean. Anyway, SciTail is actually held out from both training and evaluation, so it's probably not worth your time to fix them now, and I'd recommend just removing them from your PR.

2021-09-12 01:01 UTC, awebson approved these changes
Thank you!

2021-09-12 01:07 UTC, awebson commented
@stephenbach Would you mind taking a look at why is the check_templates test failing here? Otherwise this PR is ready to be merged. Thanks!

2021-09-12 13:18 UTC, stephenbach commented
The error is ```ValueError: Template for dataset scitail/snli_format with uuid 90827988-2a8d-4ecb-b8c1-54ad6cd0ebfa has unrecognized variable label.``` Looking at it now.

2021-09-12 13:33 UTC, stephenbach requested changes
Left comment on line that needs changing.

2021-09-12 13:33 UTC, stephenbach commented on promptsource/templates/scitail/snli_format/templates.yaml
> +      |||{% if label == "entails" %}
Looks like it should be `gold_label == "entailment"`

2021-09-12 16:59 UTC, stephenbach approved these changes

2021-09-12 16:59 UTC, merged