fix: XSum with "2nd grader" replaced and BLUE added and naming changed
bigscience-workshop/promptsource pull request #404
Opened 2021-09-11 16:02 UTC by tianjianjiang

- Mostly for #360#issuecomment-916532724
- Naming and some wording changed
  - Hopefully name changes may hint structural/orthographic differences

2021-09-11 16:18 UTC, tianjianjiang commented on promptsource/templates/xsum/templates.yaml
> +      Write a summary of the text above : ||| {{summary}}'
I guess the author of this particular template wanted to compare between prompts with or without "one sentence." 
If that's the case, this one line change shall be rejected.

2021-09-11 16:21 UTC, tianjianjiang commented on promptsource/templates/xsum/templates.yaml
> +    name: '<DOC>===given_above_write_one_sentence:'
cf.

2021-09-11 16:40 UTC, awebson requested changes
Thank you! Although could you please remove the <DOC>, etc. in template names? All punctuations will be converted to underscores, so just write a few words + whitespace/underscore is fine.

Also, could you replace triple quotes with regular quotes or just paragraph breaks? Triple quotes are not natural English.

@stephenbach Double checking: does streamlit truncate long text in rendering? In dataset viewer, some examples are clearly truncated, even though Tian-Jian simply wrote `{{document}}`.

2021-09-11 16:44 UTC, tianjianjiang commented
@awebson 
> remove the , etc. in template names? All punctuations will be converted to underscores, so just write a few words + whitespace/underscore is fine.

I see, will do! (I thought the conversion has been done by streamlit 💦 )

> Also, could you replace triple quotes with regular quotes or just paragraph breaks? Triple quotes are not natural English.

Understood! How about `===` then? I was under the impression that some of those uncommon usages were allowed before such that some templates may gain a side effect of tricking the tokenizer and the final state.

2021-09-11 16:51 UTC, awebson commented
`===` plausibly aids in human reading, and it's used by so many other templates that (a) too late to change now (b) less risk in being learned as a spurious feature of one particular task.

2021-09-11 16:54 UTC, tianjianjiang commented
@awebson Got it, thanks!

2021-09-11 16:58 UTC, tianjianjiang commented
@awebson
> `===` plausibly aids in human reading, and it's used by so many other templates that (a) too late to change now (b) less risk in being learned as a spurious feature of one particular task.

Sorry, just want to be certain. Does it still mean that I should also remove `===` from names? (I haven't checked seqio code for the conversion rules, my apologies.)

2021-09-11 17:00 UTC, awebson commented
Yes, remove === from template names but leave them them in the jinja.

2021-09-11 17:02 UTC, tianjianjiang commented
@awebson Roger that!

2021-09-11 17:25 UTC, awebson approved these changes
Thank you!

2021-09-11 17:25 UTC, awebson commented on promptsource/templates/xsum/templates.yaml
> +      So I recap it in layman''s terms: ||| {{summary}}'
```suggestion
      So I recapped it in layman''s terms: ||| {{summary}}'
```

2021-09-11 17:30 UTC, merged

2021-09-11 20:06 UTC, tianjianjiang commented on promptsource/templates/xsum/templates.yaml
> +      So I recap it in layman''s terms: ||| {{summary}}'
Ah, thank you!

2021-09-12 02:00 UTC, tianjianjiang commented
@awebson @stephenbach
> @stephenbach Double checking: is streamlit truncating long text in rendering? In dataset viewer, some examples are clearly truncated, even though Tian-Jian simply wrote `{{document}}`.

`template.apply()`'s default will truncate long strings. I'm gonna submit a simple PR for it.