Add metrics to the ade-corpus-v2 dataset
bigscience-workshop/promptsource pull request #565
Opened 2021-10-27 09:29 UTC by tae898

I used the below three rules to add metrics:

1. If specific words have to be in the answer, the metric is accuracy.
2. If a text has to be generated in the answer, the metrics are BLEU and ROUGE.

~~3. If both 1 and 2 have to be satisfied, the metrics are accuracy, BLEU, and ROUGE.~~

2021-11-01 19:40 UTC, stephenbach requested changes
Thanks! I think this dataset still needs some work.

- For the classification subset, I left a note about a minor formatting thing.
- For the other two, I think more work is needed. A lot of the prompts don't use the contextual information, resulting in prompts like
```Input

What drug has a dosage of 1500 mg/m2?
Target

methotrexate
```
This doesn't really make sense, because there's no context from which to answer the question. I think making these more like `squad` would be a lot better.

2021-11-01 19:40 UTC, stephenbach commented on promptsource/templates/ade_corpus_v2/Ade_corpus_v2_classification/templates.yaml
> +    answer_choices: Yes ||| No
This doesn't follow the required format of responding A or B if those are used to indicate choices. More generally, these just seem like weird ways of phrasing the question. Maybe both the classification tasks should just use Yes and No as the targets.

2021-11-02 10:14 UTC, tae898 commented
Thank you for the nice feedback again. I've made some changes. Please let me know if further changes are necessary.

2021-11-02 19:04 UTC, stephenbach commented
Thanks! These look great now! Just wondering, why are no prompts marked original for the relation subsets?

2021-11-02 19:13 UTC, tae898 commented
> Thanks! These look great now! Just wondering, why are no prompts marked original for the relation subsets?

AFAIK, the original authors created this dataset to train a machine-learning based classifier. The annotations from the relation subsets were used to compare the annotations between the human annotators, but they were not used to train an automatic classifier.

2021-11-02 19:16 UTC, stephenbach commented
Ah, gotcha. I think it would be fine to mark them as original task, because it's still the intended task, even if they originally used it more for testing humans.

2021-11-02 19:42 UTC, tae898 commented
> Ah, gotcha. I think it would be fine to mark them as original task, because it's still the intended task, even if they originally used it more for testing humans.

alright!

2021-11-02 20:07 UTC, stephenbach approved these changes
Thanks for all your hard work on this PR! Merging now!

2021-11-02 20:07 UTC, merged