Clean guardian_authorship
bigscience-workshop/promptsource pull request #585
Opened 2021-10-29 03:41 UTC by yongzx

Tasks:
- [X] add original tasks (≥ 5 original tasks)
- [X] add metrics
- [X] add answer choices to the field and into the prompts.
- [X] indicate answer choices in prompt if exists

Discussion:
~~Does it make sense to prompt without answer choices in the prompt? For instance, see prompt "who_wrote_article".~~ 

Edit: Reread the instructions and found my answer from instruction step 11.

2021-11-01 22:25 UTC, VictorSanh requested changes
thanks! mostly good to me.
A few changes requested:
- Don't use capitalize, directly capitalize inside the answer_choices
- Separate the names and family names in the answer_choices and in the lists of journalist names in the templates
- If you are not using "and" to list (i.e. A, B, C rather than A, B and C), you can use a simpler writing: {{answer_choices|join(", ")}}

2021-11-01 22:25 UTC, VictorSanh commented on promptsource/templates/guardian_authorship/cross_genre_1/templates.yaml
> +      \n] [author].capitalize()\n}}  on the topic of {{\n[\n  \"Politics\",\n  \"\
```suggestion
      \n] [author].capitalize()\n}} on the topic of {{\n[\n  \"Politics\",\n  \"\
```

2021-11-01 22:25 UTC, VictorSanh commented on promptsource/templates/guardian_authorship/cross_genre_1/templates.yaml
> +      \n{{article}} \n|||\n{{answer_choices[topic]}}"
```suggestion
    jinja: "What is the topic of this article? The answer options are {{answer_choices|join(\"\
      , \")}}.\n\n{{article}} \n|||\n{{answer_choices[topic]}}"
```
simpler way to write it

2021-11-01 22:25 UTC, VictorSanh commented on promptsource/templates/guardian_authorship/cross_genre_1/templates.yaml
> +      \n{{article}} \n|||\n{{answer_choices[topic]}}"
Can be applied to a lot of other places

2021-11-01 22:25 UTC, VictorSanh commented on promptsource/templates/guardian_authorship/cross_genre_1/templates.yaml
> +      ||| royhattersley ||| simonhoggart ||| willhutton ||| zoewilliams
```suggestion
    answer_choices: Catherine Bennett ||| George Monbiot ||| Hugo Young ||| Jonathan Freedland
      ||| Martin Kettle ||| Mary Riddell ||| Nick Cohen ||| Peter Preston ||| Polly Toynbee
      ||| Roy Hattersley ||| Simon Hoggart ||| Will Hutton ||| Zoe Williams
```

2021-11-01 22:25 UTC, VictorSanh commented on promptsource/templates/guardian_authorship/cross_genre_1/templates.yaml
> +      ||| royhattersley ||| simonhoggart ||| willhutton ||| zoewilliams
same for other places

2021-11-01 22:25 UTC, VictorSanh commented on promptsource/templates/guardian_authorship/cross_genre_1/templates.yaml
> +      choices_in_prompt: false
```suggestion
      choices_in_prompt: true
```

2021-11-03 16:23 UTC, yongzx commented
@VictorSanh Fixed the following:
- Answer choices (capitalize the author names and make them more natural)
- Use join instead of for-loop.
- Indicate answer choices exist in the templates.

2021-11-09 19:36 UTC, VictorSanh commented
thank you @yongzx , lgtm! merging now, i updated the spreadsheet too

2021-11-09 19:36 UTC, merged