clean art
bigscience-workshop/promptsource pull request #593
Opened 2021-10-29 13:45 UTC by zaidalyafeai

2021-11-01 19:56 UTC, stephenbach commented
Thanks! I think all of the ones that ask to output a sentence should have answer choices set, since it's either or?

2021-11-01 20:18 UTC, stephenbach commented
Also changing assignment to @awebson since this is an NLI one.

2021-11-01 20:42 UTC, zaidalyafeai commented
Thanks, Stephen. I fixed the templates.

2021-11-02 23:20 UTC, awebson requested changes
Thanks Zaid! I suggest rephrase or simply remove the following ones:

1. The "reversed" ones are not meaningfully different from each other and can artificially lower the performance variance. 
2. In `is_hyp_1 true` and `is_hyp_2 true`, you asked which one is "true". But unlike standard NLI, AbductiveNLI is not about whether the premise is strictly true, but about which option is more likely (as you noted). 
3. In `choose_hypothesis_likely`, "which version is more accurate" sounds kinda vague. "accurate" in what? (I know you mean "more likely" here, but someone who hasn't read the AbductiveNLI paper most likely won't know.)

2021-11-02 23:20 UTC, awebson commented on promptsource/templates/art/templates.yaml
> +      \ second option:\n\n{{ answer_choices[1] }}?\n|||\n{{ answer_choices[label-1]\
```suggestion
      \nWhich one is more likely?\n\nThe first option: \n\n{{ answer_choices[0] }}, \n\nor\
      \ the second option:\n\n{{ answer_choices[1] }}?\n|||\n{{ answer_choices[label-1]\
```

2021-11-03 22:09 UTC, zaidalyafeai commented
I don't feel that removing templates is a good practice. Can't we just exclude/blacklist them if they are not relative to the current use cases? Maybe we can use them as bad examples for the coming paper?

2021-11-03 22:10 UTC, zaidalyafeai commented
Between, I didn't create such templates, so I can't defend why they were written in such format.

2021-11-04 00:31 UTC, awebson commented
Well, there is a difference between prompts that read a little awkward and those that are misleading descriptions of the task in its original paper. I'm afraid the ones I pointed out are closer to the latter. 

@stephenbach Aside from the "Reference" field where you can put arbitrary string, I don't think promptsource has a metadata field for marking which ones "should be used" and which ones are saved for special purposes? 

For example I'd love to write a bunch of slight variations of one prompt for minimal pair experiments, but I want to clearly mark them with some "special experiment X" string field and be excluded by default. (Otherwise we'd artificially deflate the variance of our prompt performance.) But then I don't know if we actually want people to store their own experimental prompts and merge them into this repository?

2021-11-04 13:52 UTC, zaidalyafeai commented
My suggestion is to keep such prompts and maintain a list of prompts that we feel are not good (and why). Then we can use those prompts in the analysis paper. After that, we can decide if we want to remove/keep such prompts.

2021-11-05 22:19 UTC, zaidalyafeai commented
Changed accurate to likely. For 1. and 2. I can remove their associated templates if this is the final decision?

2021-11-07 22:23 UTC, awebson commented
Yup thanks for the "accurate" to "likely" change. And yeah removing 1 and 2 sounds good. 

I asked @stephenbach for a "final decision" but he hasn't responded yet. If we were to maintain a separate list in a Google Sheet or something, we'd have to ship/advertise that list to users of promptsource, who'd then have to implement stuff on their own to manually exclude prompts in the bad list? In which case we should just include a experiment tag + filter option in promptsource itself.

2021-11-08 11:31 UTC, zaidalyafeai commented
@awebson for the experimental prompts, I suggest doing that in a forked version of promptsource for the reasons you mentioned. For the time being, I will remove 1. and 2. since we don't have a mechanism of filtering.

2021-11-10 14:46 UTC, awebson approved these changes
Great! Thank you!

2021-11-10 14:47 UTC, merged