clean meta_woz
bigscience-workshop/promptsource pull request #602
Opened 2021-10-30 13:39 UTC by zaidalyafeai

2021-11-09 19:57 UTC, VictorSanh requested changes
lgtm, a few changes

2021-11-09 19:57 UTC, VictorSanh commented on promptsource/templates/meta_woz/dialogues/templates.yaml
> +      - BLEU
why isn't it accuracy? there are 47 choices

2021-11-09 19:57 UTC, VictorSanh commented on promptsource/templates/meta_woz/dialogues/templates.yaml
> +      - ROUGE
why isn't it accuracy?

2021-11-09 19:57 UTC, VictorSanh commented on promptsource/templates/meta_woz/dialogues/templates.yaml
> +      - BLEU
accuracy?

2021-11-09 19:57 UTC, VictorSanh commented on promptsource/templates/meta_woz/dialogues/templates.yaml
>      reference: ''
remove this one. overlappign with `predict_random_stop`

2021-11-09 22:52 UTC, zaidalyafeai commented
Is it a good idea to list that many answer choices? I suggest removing templates that predict the domain.

2021-11-12 19:54 UTC, VictorSanh commented
> Is it a good idea to list that many answer choices? I suggest removing templates that predict the domain.

I am not suggesting listing the answer_choices, I am talking about the metric. It's a 47 class classification, so the metric so reflect that

2021-11-12 20:23 UTC, zaidalyafeai commented
@VictorSanh changed it to accuracy.

2021-11-15 02:38 UTC, VictorSanh commented
great thanks @zaidalyafeai ! merging now

2021-11-15 02:38 UTC, merged