Code-related prompts
bigscience-workshop/promptsource pull request #714
Opened 2022-01-11 07:09 UTC by shakedbr

Hi,
I contributed the following prompts:

**Dataset**: great_code
**Prompts**:

1. _bug detection_: Given a function, predict whether there is a bug in the code.
2. _fix buggy line_: Given a function and a buggy line, fix the buggy line.
3. _function name generation_: Given a function body, generate the function name.
4. _identifier prediction no choices_: Given a code with a masked identifier, generate it, (without choices).
5. _identifier prediction with choices_: Given a code with a masked identifier, generate it, (with choices).

**Dataset**: openai_humaneval
**Prompts**:
1. _function body generation_: Given a function signature and docstring, generate the function body.
2. _test_x return value generation_ <img src="https://render.githubusercontent.com/render/math?math=(x\in[10])">: Given a function body and a call, predict the return value of test x.

**Dataset**: code_x_glue_tc_text_to_code
**Prompts**:
1. _generate class member function given class environment_: : Given a class members (methods and fields) and a method description, generate the method.

**Dataset**: neural_code_search
**Prompts**:
1. _generate a description given code_: Given a code snippet, generate a natural language description.
2.  _generate code given a description_: Given a description, generate code.

2022-01-26 22:05 UTC, VictorSanh commented
thank you for your patience @shakedbr 
These are very complicated datasets, thanks for working on this!
I left a few comments, questions and suggested fixes for missing metrics.

2022-01-31 09:44 UTC, shakedbr commented
Hi @VictorSanh, I can't see any comments

2022-01-31 14:10 UTC, VictorSanh requested changes
oooops @shakedbr, my bad, I never pushed out the review I started...

2022-02-01 07:27 UTC, shakedbr commented on promptsource/templates/neural_code_search/evaluation_dataset/templates.yaml
> +dataset: neural_code_search
The original task is to search for code given some natural language description (e.g. in some database)., therefore none of the above is the original task. "generate code given a description" is the closest one.

2022-02-01 07:35 UTC, shakedbr commented on promptsource/templates/great_code/templates.yaml
> +dataset: great_code
The original task - VarMisuse, aims to look for a certain type of bug - a wrong usage of some variable e.g. 
```python
a = 1
b = 2
sum_a_b = add(a, a)
```
 which can be compiled without raising any errors, but it should be 
```python
a = 1
b = 2
sum_a_b = add(a, b)
```
Thus, none of the above prompts is the **exact** original task (which requires locating and fixing the bug).

2022-02-01 07:58 UTC, shakedbr commented on promptsource/templates/openai_humaneval/templates.yaml
> +dataset: openai_humaneval
fixed

2022-02-01 07:58 UTC, shakedbr commented on promptsource/templates/great_code/templates.yaml
> +    name: bug detection
fixed

2022-02-01 07:59 UTC, shakedbr commented
@VictorSanh I addressed all your questions and comments

2022-02-04 19:07 UTC, VictorSanh commented
thanks @shakedbr !

I added a few more fixes (in particular setting the variables outside of the conditional statements to avoid the `Undefined variable` error)

Could you pull from master so that you can run the tests? 
I ran them locally and all except one fail:
The last bug I have is for `fix buggy line` on `great_code` on test set (3rd example i.e. `id=2`)
<img width="1407" alt="Capture d’écran 2022-02-04 à 2 05 09 PM" src="https://user-images.githubusercontent.com/16107619/152588222-756628b9-35d1-4adc-a988-aa68d314bb5e.png">

2022-02-06 08:41 UTC, shakedbr commented
@VictorSanh sorry for the errors.
I fixed the stuff and run the test locally, and it seems to work.

2022-02-14 21:00 UTC, VictorSanh commented
Ran the tests locally and it works just fine!
merging now, thanks @shakedbr !

2022-02-14 21:00 UTC, merged

2022-08-12 18:25 UTC, Muennighoff commented on promptsource/templates/openai_humaneval/templates.yaml
> +      Given the following docstring, what is the function body?
This should probably be "GIven the above"; Anyways this prompt is bad imo as there's a function name + a docstring above.

Would be better to have e.g. "Complete the following function\n{{ prompt }}" imo