add Zest
bigscience-workshop/promptsource pull request #73
Opened 2021-06-04 20:49 UTC by VictorSanh

2021-06-04 21:09 UTC, srush commented
Do we allow different templates for splits? I thought it was just the sub-groups.

2021-06-04 21:14 UTC, VictorSanh commented
> Do we allow different templates for splits? I thought it was just the sub-groups.

No, right now we don't have such a logic (different templates for different split).
For the sake of simplicity, I think we should check before applying the jinja whether all the fields are present. I can imagine that for many datasets, the test split just doesn't have the fields we use as labels.

2021-06-04 21:19 UTC, srush requested changes

2021-06-04 21:19 UTC, srush commented on templates/zest/templates.yaml
> +      answer[0]
Needs to be in a {{ }}

2021-06-04 21:19 UTC, srush commented on templates/zest/templates.yaml
> +      Based on the previous passage, generate a question which has for answer {{answer[0]}}.
has "the following passage for an answer"

2021-06-04 21:19 UTC, srush commented on templates/zest/templates.yaml
> +      answer[0]
Needs to be {{ }}

2021-06-04 21:19 UTC, srush commented on templates/zest/templates.yaml
> +    jinja: 'Answer this question about {{domain}} based on the context. If the question
domain is of the form "national_parks" I think you could replace the "_" with a space?

2021-06-04 21:19 UTC, srush commented on templates/zest/templates.yaml
> +      answer[0]
Needs to be {{ }}

2021-06-07 01:06 UTC, srush approved these changes

2021-06-07 01:06 UTC, merged