remove language restrictions
bigscience-workshop/promptsource pull request #763
Opened 2022-05-05 15:54 UTC by KhalidAlt

2022-05-05 18:06 UTC, stephenbach commented
Can you make this PR target the eval-hackathon branch? Thanks!

2022-06-29 23:24 UTC, VictorSanh commented
@KhalidAlt what is `template.yaml.save` and `template.yaml.save.1`? Can we remove them?

2022-06-30 06:06 UTC, KhalidAlt commented
Hi @VictorSanh, I think you can remove them.

2022-06-30 19:16 UTC, VictorSanh commented
@KhalidAlt there are still errors in tests for some reason, if you can get to it before please do, I have a few things to sort out this afternoon first

2022-08-09 18:02 UTC, stephenbach commented
Sorry, I took so long to look at this that it's fallen out of date. Can you resolve the conflicts and I can take another look?

2022-08-09 18:16 UTC, zaidalyafeai commented
If u need some help I can review the prompts.

2022-08-16 06:29 UTC, KhalidAlt commented
Hi @zaidalyafeai, It will be so helpful if you can review the Arabic prompts. Thanks a lot.

2022-08-16 19:48 UTC, KhalidAlt commented
Hi @zaidalyafeai, I think you can review the prompts much easier now. I fixed the Unicode characters problem and it shows the Arabic characters now.

2022-08-16 20:11 UTC, KhalidAlt commented
Hi @stephenbach, I fixed all the conflicts and a small bug that prevent Unicode characters from showing properly in .yaml files. Please let me know if there is anything need change. Also, show_new_templates check is always failing due to large size of data.

2022-08-17 17:06 UTC, zaidalyafeai commented
@KhalidAlt the branch seems to include many other commits for other languages?

2022-08-21 10:13 UTC, KhalidAlt commented
@zaidalyafeai, previously, Unicode characters were saved on byte format. Therefore, I fixed the issue, and most prompts have changed from byte to Unicode. This is the reason that there are many other commits for other languages. Please let me know if anything to be changed. Thanks

2022-08-21 10:34 UTC, zaidalyafeai commented
Sure will review prompts today.

2022-08-21 16:40 UTC, zaidalyafeai requested changes

2022-08-21 16:40 UTC, zaidalyafeai commented on promptsource/templates/tydiqa/primary_task/templates.yaml
> +      \ من ويكبيديا أجب عن السؤال التالي:\n{{question_text}} \n{{document_plaintext}}\n\
المقتبس؟

2022-08-21 16:40 UTC, zaidalyafeai commented on promptsource/templates/tydiqa/secondary_task/templates.yaml
> +      \ %}\nلطالما تسائلت حول: {{question}}\nبحث في ويكيبيديا ووجدت نص بعنوان {{title}}.\n\
بحثت

2022-08-21 16:40 UTC, zaidalyafeai commented on promptsource/templates/tydiqa/secondary_task/templates.yaml
> +      \ %}\nالنص: {{context}}\nاجابة هذا السؤال  \"{{question}}\" موجودة في النص المقتطع\
كلمة النص متكررة مرتان

2022-08-21 16:40 UTC, zaidalyafeai commented on promptsource/templates/tydiqa/secondary_task/templates.yaml
> +      \ بعنوان: {{title}}. هل يمكنك الإجابة عن السؤال؟\n|||\n{{answers.text | choice}}\n\
Is `answer.text` yes or no? The question seems to require that.

2022-10-26 05:58 UTC, samsontmr commented
@KhalidAlt @stephenbach Any chance we can get this merged soon? We need the filter to be removed before we can run the evaluations for the paper. Thanks!

2022-10-26 14:55 UTC, VictorSanh commented
@KhalidAlt it the tests pass locally, and @zaidalyafeai has validated, i can merge this in

2022-10-26 14:57 UTC, stephenbach commented
Whoops, I DMed @KhalidAlt. Please don’t merge yet. There’s some code duplication in templates.py that needs to be removed.

2022-10-26 16:09 UTC, KhalidAlt commented
Hi @stephenbach, I removed the code duplication. I used the argument (allow_unicode=True) because non-ASCII language prompts were saved in byte formatting which makes it difficult to review them manually using a .ymal file.

2022-10-26 20:53 UTC, stephenbach commented
There's a .app.py.swp in the changes.

2022-10-26 21:04 UTC, KhalidAlt commented
Hi @stephenbach, I have deleted it in the cleaning commit.

2022-10-26 21:12 UTC, stephenbach commented
For the record, show_new_templates fails because the dataset is too big to run on GitHub and check_templates fails because of the issue that #832 addresses.

2022-10-26 21:12 UTC, stephenbach approved these changes
LGTM!

2022-10-26 21:12 UTC, merged