templates for wiki_qa dataset
bigscience-workshop/promptsource pull request #97
Opened 2021-06-07 08:30 UTC by lintangsutawika

2021-06-07 20:21 UTC, VictorSanh commented on templates/wiki_qa/templates.yaml
> +      Determine if the topic of the question-answer pair.
typo: no need for "if"

2021-06-07 20:22 UTC, VictorSanh commented on templates/wiki_qa/templates.yaml
> +      Question: "{{question}}?";  Answer: "{{answer}}"?|||
`|||` -> `Topic: ||| "{{document_title}}"

2021-06-07 20:22 UTC, VictorSanh commented on templates/wiki_qa/templates.yaml
> +      Determine if the topic of the question-answer pair.
same for Topic Prediction - Question only

2021-06-07 20:23 UTC, VictorSanh commented on templates/wiki_qa/templates.yaml
> +      Question: "{{question}}?";  Answer: "{{answer}}"?|||
same for Topic Prediction - Question only

2021-06-07 20:25 UTC, VictorSanh requested changes
Thanks @lintangsutawika, lgtm!

Flagged some small typos in comments, I'll merge once you have changed these

2021-06-08 01:41 UTC, lintangsutawika commented
@VictorSanh Sorry for the typos. They are fixed now.

2021-06-08 02:33 UTC, VictorSanh approved these changes

2021-06-08 02:35 UTC, VictorSanh commented
thanks, merging now!

2021-06-08 02:35 UTC, merged